"""Keep this demo on the current GemStone MCP server, and prove it still works.

    python3 refresh_mcp.py                 # what is upstream, staged, installed
    python3 refresh_mcp.py --install       # fetch the latest and file it in
    python3 refresh_mcp.py --verify        # run the promises over MCP
    python3 refresh_mcp.py --install --verify --ref v0.7.0

The MCP server is a moving target -- it lives in its own repository, ships on
its own schedule, and the copy GemDB bundles is pinned to whenever GemDB was
packaged. This demo talks to it over a protocol, so an upgrade can change the
answers without changing a line of this repo.

**Updating and verifying are one command on purpose.** Chasing a moving target
is only safe if something checks afterwards, and the thing worth checking is
not "does it start" but "do the questions this demo promises still return the
answers it promises". Those live in `docs/mcp-questions.md`, generated by
running them, so this reads that file rather than restating it: a snippet and
the answer printed beneath it are a promise, and drift is a broken promise.

WHY THIS ASSEMBLES ITS OWN PAYLOAD

It does not use `GemDB_Code/scripts/bundle-mcp.sh`. That script copies a
hardcoded list of shell scripts which omits `session-lifetime.sh`, so the
payload it produces cannot start its own server. This copies every
`.sh` the upstream tree has, which is the fix that bug wants.

WHAT IT WILL NOT DO

It never reinstalls Grail and never re-seeds. Filing the `Mcp*` classes in is
additive -- nothing user-side reads them -- and the seeded book is checked
before and after so that claim is measured rather than assumed.
"""

import argparse
import collections
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import socket
import urllib.request

UPSTREAM = "https://github.com/GemTalk/mcp_server.git"
GEMDB_ROOT = os.path.expanduser("~/GemDB")
MCP_DIR = os.path.join(GEMDB_ROOT, "mcp")
STAMP = os.path.join(MCP_DIR, "MCP_VERSION")
HERE = os.path.dirname(os.path.abspath(__file__))
DOC = os.path.join(HERE, "docs", "mcp-questions.md")
PORT = 50390

#: Not `main` -- `__main__` is one namespace shared by every script this
#: database has ever run, and dispatch is by argument count. See finding 2.
Promise = collections.namedtuple("Promise", "title code answer")


# ---------------------------------------------------------------- stamps ---

def parse_stamp(text):
    """`key=value` lines into a dict. Unknown keys are kept, not dropped."""
    out = {}
    for line in (text or "").splitlines():
        if "=" in line:
            key, _, value = line.partition("=")
            out[key.strip()] = value.strip()
    return out


def has_drifted(staged, upstream):
    """True when what is staged is not what upstream now points at.

    Shas are compared by prefix in both directions: a stamp records a short
    sha and `git ls-remote` reports a full one, and neither is more correct.
    """
    if not staged or not upstream:
        return True
    return not (upstream.startswith(staged) or staged.startswith(upstream))


def staged_commit():
    try:
        with open(STAMP) as handle:
            return parse_stamp(handle.read()).get("commit")
    except IOError:
        return None


def upstream_head(ref=None):
    """The sha upstream's default branch (or `ref`) points at, without cloning."""
    args = ["git", "ls-remote", UPSTREAM] + ([ref] if ref else ["HEAD"])
    out = subprocess.run(args, capture_output=True, text=True)
    if out.returncode != 0 or not out.stdout.strip():
        raise SystemExit("could not reach %s\n%s" % (UPSTREAM, out.stderr[:300]))
    return out.stdout.split()[0]


# -------------------------------------------------------------- promises ---

def promises(markdown):
    """Every (snippet, printed answer) pair under a `##` heading, in order.

    The preamble at the top of the document is a snippet with no answer under
    it, and it sits above every heading; requiring a heading is what excludes
    it without naming it.
    """
    found = []
    title = None
    pending = None
    fence = None
    buffer = []

    for line in markdown.splitlines():
        if fence is None:
            if line.startswith("## "):
                title, pending = line[3:].strip(), None
            elif line.startswith("```"):
                fence, buffer = line[3:].strip() or "text", []
            continue
        if line.startswith("```"):
            body = "\n".join(buffer).strip("\n")
            if title is not None:
                if fence == "python":
                    pending = body
                elif pending is not None:
                    found.append(Promise(title, pending, body))
                    pending = None
            fence = None
        else:
            buffer.append(line)
    return found


def published_preamble(markdown):
    """The `python` block above the first `##` heading, or None.

    Read back rather than restated. The document says "each snippet assumes
    this preamble", and the generator used to run a different one -- so
    the published preamble could not run the questions printed beneath it and
    nothing caught it. Lifting it from the document is what makes verification
    exercise the reader's path instead of a private one.
    """
    fence = None
    buffer = []
    for line in markdown.splitlines():
        if line.startswith("## "):
            return None                     # reached a question first
        if fence is None:
            if line.startswith("```"):
                fence = line[3:].strip() or "text"
                buffer = []
            continue
        if line.startswith("```"):
            if fence == "python":
                return "\n".join(buffer).strip("\n")
            fence = None
        else:
            buffer.append(line)
    return None


def read_promises():
    with open(DOC) as handle:
        return promises(handle.read())


# ----------------------------------------------------------- environment ---

def gemstone_env():
    """What topaz needs, in the shape `~/GemDB/bin/gemdb` proved works.

    `GEMSTONE_NRS_ALL` is the one that is easy to miss and hard to diagnose:
    the router forks its workers through a NetLDI, and without this it looks
    for `gs64ldi` while GemDB's is `gemdbldi`, failing with a `getaddrinfo`
    error that reads like DNS.
    """
    engine = os.path.join(GEMDB_ROOT, "GemStone64Bit3.7.5-arm64.Darwin")
    grail = os.path.join(GEMDB_ROOT, "grail")
    env = dict(os.environ)
    env.update({
        "GEMSTONE": engine,
        "GEMSTONE_GLOBAL_DIR": GEMDB_ROOT,
        "GEMSTONE_SYS_CONF": os.path.join(GEMDB_ROOT, "db", "conf"),
        "GEMSTONE_EXE_CONF": os.path.join(GEMDB_ROOT, "db", "conf"),
        "GEMSTONE_NRS_ALL": "#netldi:gemdbldi#dir:%s#log:%s" % (
            os.path.join(GEMDB_ROOT, "db"),
            os.path.join(GEMDB_ROOT, "db", "log", "%N_%P.log")),
        "GRAIL_DIR": grail,
        "PYTHON_PACKAGE_PATH": os.path.join(grail, "src", "python"),
        "SHIM_LIB_PATH": os.path.join(grail, "src", "c", "shim", "libcpython_ua.dylib"),
        "DYLD_LIBRARY_PATH": os.path.join(engine, "lib"),
        "PATH": os.path.join(engine, "bin") + ":" + os.environ.get("PATH", ""),
        "GS_STONE": "gemdb",
        "GS_USER": "DataCurator",
        "GS_PASS": "swordfish",
        "MCP_PORT": str(PORT),
        "MCP_GRAIL_DIR": grail,
    })
    return env


# --------------------------------------------------------------- install ---

def install(ref=None):
    """Clone upstream, assemble the payload, stage it, file it in."""
    work = tempfile.mkdtemp(prefix="mcp-")
    source = os.path.join(work, "mcp_server")
    try:
        clone = ["git", "clone", "--depth", "1"]
        if ref:
            clone += ["--branch", ref]
        run(clone + [UPSTREAM, source], "clone")

        sha = subprocess.run(["git", "-C", source, "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True).stdout.strip()
        print("  upstream %s" % sha)

        shutil.rmtree(MCP_DIR, ignore_errors=True)
        os.makedirs(MCP_DIR)
        shutil.copytree(os.path.join(source, "src"), os.path.join(MCP_DIR, "src"))
        # Every .sh, not a list of them -- see the module docstring.
        copied = 0
        for name in sorted(os.listdir(source)):
            path = os.path.join(source, name)
            if os.path.isfile(path) and (name.endswith(".sh") or
                                         name in ("load.gs", "LICENSE", "README.md")):
                shutil.copy(path, os.path.join(MCP_DIR, name))
                if name.endswith(".sh"):
                    os.chmod(os.path.join(MCP_DIR, name), 0o755)
                    copied += 1
        print("  staged %d shell scripts to %s" % (copied, MCP_DIR))
        missing = unreferenced_scripts()
        if missing:
            raise SystemExit("payload references scripts it does not have: %s"
                             % ", ".join(sorted(missing)))

        with open(STAMP, "w") as handle:
            handle.write("mcp=%s\ncommit=%s\nurl=%s\n" % (sha, sha, UPSTREAM))

        run(["bash", "install.sh", "--grail", "--no-auth"], "install",
            cwd=MCP_DIR, env=gemstone_env())
        print("  filed into the database and committed")
        return sha
    finally:
        shutil.rmtree(work, ignore_errors=True)


def unreferenced_scripts():
    """Scripts the staged payload calls but does not contain."""
    wanted = set()
    for name in os.listdir(MCP_DIR):
        if not name.endswith(".sh"):
            continue
        with open(os.path.join(MCP_DIR, name)) as handle:
            wanted |= set(re.findall(r"\./([A-Za-z0-9_-]+\.sh)", handle.read()))
    return {s for s in wanted if not os.path.exists(os.path.join(MCP_DIR, s))}


def run(args, what, cwd=None, env=None):
    out = subprocess.run(args, capture_output=True, text=True, cwd=cwd, env=env)
    if out.returncode != 0:
        sys.stderr.write(out.stdout[-2000:] + out.stderr[-2000:])
        raise SystemExit("%s failed" % what)
    return out.stdout


# ---------------------------------------------------------------- verify ---

class Client:
    """One MCP session, and only one.

    Each client costs a worker gem, the router caps them at three and the stone
    allows ten. A verifier that opened a session per question would be the
    pathological case the cap exists to refuse.
    """

    def __init__(self, port=PORT):
        self.url = "http://127.0.0.1:%d/mcp" % port
        self.session = None
        self.next_id = 1

    def rpc(self, method, params=None, notify=False):
        body = {"jsonrpc": "2.0", "method": method}
        if params is not None:
            body["params"] = params
        if not notify:
            body["id"] = self.next_id
            self.next_id += 1
        headers = {"Content-Type": "application/json",
                   "Accept": "application/json, text/event-stream"}
        if self.session:
            headers["Mcp-Session-Id"] = self.session
        request = urllib.request.Request(
            self.url, data=json.dumps(body).encode(), headers=headers, method="POST")
        with urllib.request.urlopen(request, timeout=300) as response:
            got = response.headers.get("Mcp-Session-Id")
            if got and not self.session:
                self.session = got
            raw = response.read().decode()
        if not raw.strip():
            return None
        for line in raw.splitlines():
            if line.startswith("data:"):
                return json.loads(line[5:].strip())
        return json.loads(raw)

    def open(self):
        hello = self.rpc("initialize", {
            "protocolVersion": "2025-06-18", "capabilities": {},
            "clientInfo": {"name": "brain-freeze-refresh", "version": "1"}})
        if "error" in (hello or {}):
            raise SystemExit("initialize refused: %s" % hello["error"].get("message"))
        self.rpc("notifications/initialized", {}, notify=True)
        return hello["result"]["serverInfo"]

    def close(self):
        try:
            request = urllib.request.Request(
                self.url, headers={"Mcp-Session-Id": self.session or ""}, method="DELETE")
            urllib.request.urlopen(request, timeout=30).read()
        except Exception:
            pass                      # the router reaps it; never fail on cleanup

    def python(self, code):
        out = self.rpc("tools/call", {"name": "eval_python",
                                      "arguments": {"code": code}})
        result = out.get("result", out)
        return "\n".join(part.get("text", "")
                         for part in result.get("content", [])).strip()


def router(action):
    run(["bash", "%s-server.sh" % action], "%s-server" % action,
        cwd=MCP_DIR, env=gemstone_env())


def router_is_listening(port=PORT):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.settimeout(1.0)
        return probe.connect_ex(("127.0.0.1", port)) == 0


def verify():
    """Ask every promise over MCP, and leave the router as we found it.

    A router already listening is the NORMAL case once someone has connected
    a client: it is a long-lived server, and Claude Code keeps pointing at it.
    An earlier version of this assumed the port was free, tried to start a
    second router, and reported `run-server failed` -- which says nothing
    about the actual situation and sent me looking for a broken payload.

    So: if one is already there, use it and say so, and do NOT stop it on the
    way out. Stopping a server this script did not start would take somebody's
    connected agent down with it.
    """
    expected = read_promises()
    print("  %d promises in docs/mcp-questions.md" % len(expected))

    borrowed = router_is_listening()
    if borrowed:
        print("  a router is already serving on port %d -- using it, and" % PORT)
        print("  leaving it running. Its version is reported below.")
    else:
        router("run")

    client = Client()
    try:
        info = client.open()
        print("  server %s %s" % (info.get("name"), info.get("version")))
        tools = client.rpc("tools/list")["result"]["tools"]
        print("  %d tools offered" % len(tools))
        if not any(t["name"] == "eval_python" for t in tools):
            raise SystemExit("no eval_python: this server cannot answer anything")

        client.python(preamble())
        kept = broken = 0
        for promise in expected:
            got = client.python(promise.code)
            if got.strip() == promise.answer.strip():
                kept += 1
            else:
                broken += 1
                print("\n  BROKEN  %s" % promise.title)
                print("    promised: %s" % promise.answer)
                print("    returned: %s" % got)
        print("\n  %d kept, %d broken" % (kept, broken))
        return 1 if broken else 0
    finally:
        client.close()
        if borrowed:
            print("  router left running -- it was not ours to stop")
        else:
            router("stop")
            print("  router stopped")


def preamble():
    """The document's own preamble, plus the path it does not have to mention.

    The imports are LIFTED from docs/mcp-questions.md rather than written out
    here. A private copy is how that bug survived: the document published a
    preamble that could not run its own question 6, and every check passed
    because nothing checked ran what the document said.

    The `sys.path` line is the one honest addition. A worker gem's working
    directory is the stone's, so `brainfreeze` is not importable until the
    repository is on the path; in a notebook or a script the directory is
    already there, which is why the document does not carry it.
    """
    with open(DOC) as handle:
        published = published_preamble(handle.read())
    if published is None:
        raise SystemExit("%s publishes no preamble to run" % DOC)
    return "import sys\nsys.path.insert(0, %r)\n%s\n" % (HERE, published)


# ------------------------------------------------------------------ main ---

def refresh():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--install", action="store_true",
                        help="stage and file in the latest upstream server")
    parser.add_argument("--verify", action="store_true",
                        help="run docs/mcp-questions.md over MCP")
    parser.add_argument("--ref", help="a tag or branch instead of the default branch")
    args = parser.parse_args()

    head = upstream_head(args.ref)
    staged = staged_commit()
    drifted = has_drifted(staged, head)

    print("upstream  %s%s" % (head[:12], " (%s)" % args.ref if args.ref else ""))
    print("staged    %s" % (staged or "nothing staged"))
    print("verdict   %s" % ("BEHIND -- run with --install" if drifted
                            else "current"))

    if args.install:
        print("\ninstalling:")
        install(args.ref)
    if args.verify:
        print("\nverifying:")
        return verify()
    if drifted and not args.install:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(refresh())
