"""The questions an agent is asked, and a client to ask them over MCP.

docs/mcp-questions.md publishes a preamble and a set of questions, each a
Python snippet with the answer it prints beneath it. This reads them back, so
the tests exercise what the document says rather than a private copy, and
`Client` asks them of the MCP server GemDB Code bundles -- step 5 of the
tutorial, in features/5_mcp.feature.

The document itself is generated by tools/make_mcp_questions.py.
"""

import collections
import json
import os
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC = os.path.join(REPO, "docs", "mcp-questions.md")

Promise = collections.namedtuple("Promise", "title code answer")


def promises(markdown):
    """Every (snippet, printed answer) pair under a `##` heading, in order.

    The preamble at the top of the document is a snippet with no answer under
    it, and it sits above every heading; requiring a heading is what excludes
    it without naming it.
    """
    found = []
    title = None
    pending = None
    fence = None
    buffer = []

    for line in markdown.splitlines():
        if fence is None:
            if line.startswith("## "):
                title, pending = line[3:].strip(), None
            elif line.startswith("```"):
                fence, buffer = line[3:].strip() or "text", []
            continue
        if line.startswith("```"):
            body = "\n".join(buffer).strip("\n")
            if title is not None:
                if fence == "python":
                    pending = body
                elif pending is not None:
                    found.append(Promise(title, pending, body))
                    pending = None
            fence = None
        else:
            buffer.append(line)
    return found


def published_preamble(markdown):
    """The `python` block above the first `##` heading, or None.

    Read back rather than restated. The document says "each snippet assumes
    this preamble", and the generator used to run a different one -- so
    the published preamble could not run the questions printed beneath it and
    nothing caught it. Lifting it from the document is what makes verification
    exercise the reader's path instead of a private one.
    """
    fence = None
    buffer = []
    for line in markdown.splitlines():
        if line.startswith("## "):
            return None                     # reached a question first
        if fence is None:
            if line.startswith("```"):
                fence = line[3:].strip() or "text"
                buffer = []
            continue
        if line.startswith("```"):
            if fence == "python":
                return "\n".join(buffer).strip("\n")
            fence = None
        else:
            buffer.append(line)
    return None


def read_promises():
    with open(DOC) as handle:
        return promises(handle.read())


def preamble():
    """The document's own preamble, plus the path it does not have to mention.

    The imports are LIFTED from docs/mcp-questions.md rather than written out
    here. A private copy is how that bug survived: the document published a
    preamble that could not run its own question 6, and every check passed
    because nothing checked ran what the document said.

    The `sys.path` line is the one honest addition. A worker gem's working
    directory is the stone's, so `brainfreeze` is not importable until the
    repository is on the path; in a notebook or a script the directory is
    already there, which is why the document does not carry it.
    """
    with open(DOC) as handle:
        published = published_preamble(handle.read())
    if published is None:
        raise SystemExit("%s publishes no preamble to run" % DOC)
    return "import sys\nsys.path.insert(0, %r)\n%s\n" % (REPO, published)


class Client:
    """One MCP session, and only one.

    Each client costs a worker gem, the router caps them at three and the stone
    allows ten. A verifier that opened a session per question would be the
    pathological case the cap exists to refuse.
    """

    def __init__(self, port):
        self.url = "http://127.0.0.1:%d/mcp" % port
        self.session = None
        self.next_id = 1

    def rpc(self, method, params=None, notify=False):
        body = {"jsonrpc": "2.0", "method": method}
        if params is not None:
            body["params"] = params
        if not notify:
            body["id"] = self.next_id
            self.next_id += 1
        headers = {"Content-Type": "application/json",
                   "Accept": "application/json, text/event-stream"}
        if self.session:
            headers["Mcp-Session-Id"] = self.session
        request = urllib.request.Request(
            self.url, data=json.dumps(body).encode(), headers=headers, method="POST")
        with urllib.request.urlopen(request, timeout=300) as response:
            got = response.headers.get("Mcp-Session-Id")
            if got and not self.session:
                self.session = got
            raw = response.read().decode()
        if not raw.strip():
            return None
        for line in raw.splitlines():
            if line.startswith("data:"):
                return json.loads(line[5:].strip())
        return json.loads(raw)

    def open(self):
        hello = self.rpc("initialize", {
            "protocolVersion": "2025-06-18", "capabilities": {},
            "clientInfo": {"name": "brain-freeze", "version": "1"}})
        if "error" in (hello or {}):
            raise SystemExit("initialize refused: %s" % hello["error"].get("message"))
        self.rpc("notifications/initialized", {}, notify=True)
        return hello["result"]["serverInfo"]

    def close(self):
        try:
            request = urllib.request.Request(
                self.url, headers={"Mcp-Session-Id": self.session or ""}, method="DELETE")
            urllib.request.urlopen(request, timeout=30).read()
        except Exception:
            pass                      # the router reaps it; never fail on cleanup

    def python(self, code):
        out = self.rpc("tools/call", {"name": "eval_python",
                                      "arguments": {"code": code}})
        result = out.get("result", out)
        return "\n".join(part.get("text", "")
                         for part in result.get("content", [])).strip()
